import { DIMENSIONS, type TasteVector } from "./dimensions";
import { styleName } from "./name";
import type { Tokens } from "./tokens";

function pct(x: number): number {
  return Math.round(x * 100);
}

// Turn the taste vector into prose directives. This is a deterministic stand-in
// for the "LLM-written style guide" — same shape, zero network dependency.
function proseGuide(t: TasteVector, tokens: Tokens): string[] {
  const lines: string[] = [];

  lines.push(
    t.radius < 0.25
      ? `Use sharp corners. Border radius should be ${tokens.radiusPx}px or less.`
      : t.radius > 0.75
        ? `Prefer generously rounded corners (~${tokens.radiusPx}px). Pills for buttons.`
        : `Use moderate corner radii around ${tokens.radiusPx}px.`,
  );

  lines.push(
    t.gradients > 0.55
      ? "Gradients are welcome on primary surfaces and hero areas."
      : "Never use gradients. Keep fills flat and solid.",
  );

  lines.push(
    t.density > 0.6
      ? "Favor dense, information-rich layouts with tight spacing."
      : t.density < 0.35
        ? "Favor airy layouts with lots of whitespace."
        : "Balance density — neither cramped nor sparse.",
  );

  lines.push(
    `Type: ${tokens.fontName}. Display weight ${tokens.fontWeightDisplay}, body weight ${tokens.fontWeightBody}.`,
  );

  lines.push(
    t.mode > 0.6
      ? "Default to a dark UI."
      : t.mode < 0.4
        ? "Default to a light UI."
        : "Support both light and dark, leaning neutral.",
  );

  lines.push(
    t.saturation > 0.6
      ? "Colors should be vivid and confident."
      : t.saturation < 0.35
        ? "Keep colors muted and restrained."
        : "Use moderate color saturation.",
  );

  lines.push(
    t.depth > 0.6
      ? "Use layered shadows and elevation to create depth."
      : "Keep surfaces flat; avoid heavy shadows.",
  );

  if (t.ornament > 0.55) lines.push("Decorative details and ornament are on-brand.");
  else lines.push("Stay minimal. Avoid decorative ornament.");

  lines.push(
    t.motion > 0.6
      ? "Motion is expressive — animate transitions and micro-interactions."
      : "Keep motion subtle and quick.",
  );

  return lines;
}

export interface TasteFile {
  fileName: string;
  content: string;
}

// Produce the wedge artifact: a Cursor rules file capturing the taste as both
// machine-readable tokens and a human style guide.
export function generateTasteFile(
  t: TasteVector,
  tokens: Tokens,
  hue: number,
  swipeCount: number,
): TasteFile {
  const name = styleName(t, hue);

  const dims: Record<string, number> = {};
  for (const d of DIMENSIONS) dims[d.key] = pct(t[d.key]);

  const tokenJson = {
    name,
    hue: Math.round(hue),
    dimensions: dims,
    resolved: {
      palette: tokens.palette,
      radiusPx: tokens.radiusPx,
      spaceUnitPx: tokens.spaceUnitPx,
      fontDisplay: tokens.fontDisplay,
      fontBody: tokens.fontBody,
      fontWeightDisplay: tokens.fontWeightDisplay,
      fontWeightBody: tokens.fontWeightBody,
    },
  };

  const prose = proseGuide(t, tokens)
    .map((l) => `- ${l}`)
    .join("\n");

  const content = `---
description: Personal design taste "${name}", learned by swiping in Taste Engine. Apply to all UI work.
globs: ["**/*.tsx", "**/*.jsx", "**/*.css", "**/*.html"]
alwaysApply: true
---

# Design taste: ${name}

You are building UI for someone with a specific, measured visual taste.
Honor these directives on every component, page, and style you produce.

## Style directives
${prose}

## Design tokens (source of truth)
\`\`\`json
${JSON.stringify(tokenJson, null, 2)}
\`\`\`

## CSS variables
\`\`\`css
:root {
${Object.entries(tokens.cssVars)
  .map(([k, v]) => `  ${k}: ${v};`)
  .join("\n")}
}
\`\`\`

_Generated by Taste Engine from ${swipeCount} swipes. You never described this — you reacted, and it compiled._
`;

  return { fileName: ".cursor/rules/taste.mdc", content };
}
