import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { extractSignals } from "./cssSignals";
import { normalizeSignals, type ScrapedCard } from "./normalize";
import { CORPUS_SITES, HOLDOUT_SITES } from "./sites";

// pnpm scrape          -> bench/data/scraped-corpus.json (feeds src/corpus/scraped.ts)
// pnpm scrape:holdout  -> bench/data/holdout.json (hidden eval only, never imported into src/)
async function main() {
  const target = process.argv[2] ?? "corpus";
  const sites = target === "holdout" ? HOLDOUT_SITES : CORPUS_SITES;
  const outPath =
    target === "holdout"
      ? new URL("../data/holdout.json", import.meta.url)
      : new URL("../data/scraped-corpus.json", import.meta.url);

  const cards: ScrapedCard[] = [];
  const failures: string[] = [];

  for (const url of sites) {
    process.stderr.write(`scraping ${url} ... `);
    try {
      const sig = await extractSignals(url);
      if (!sig || sig.declarationCount < 5) {
        failures.push(url);
        process.stderr.write("no usable CSS\n");
        continue;
      }
      cards.push(normalizeSignals(sig));
      process.stderr.write("ok\n");
    } catch (err) {
      failures.push(url);
      process.stderr.write(`failed: ${(err as Error).message}\n`);
    }
  }

  writeFileSync(fileURLToPath(outPath), JSON.stringify(cards, null, 2) + "\n");
  process.stderr.write(`\nwrote ${cards.length}/${sites.length} cards to ${fileURLToPath(outPath)}\n`);
  if (failures.length) process.stderr.write(`failed: ${failures.join(", ")}\n`);

  if (target === "corpus") writeShippedCorpus(cards);
}

// Emits src/corpus/scraped.ts — a plain, static, committed TS module (no
// runtime scraping in the shipped app). Re-run `pnpm scrape` to refresh it.
function writeShippedCorpus(cards: ScrapedCard[]) {
  const entries = cards
    .map((c) => {
      const attrs = Object.entries(c.attrs)
        .map(([k, v]) => `      ${k}: ${(v as number).toFixed(3)},`)
        .join("\n");
      return `  {
    id: "${c.id}",
    name: ${JSON.stringify(c.name)},
    tagline: ${JSON.stringify(c.tagline)},
    hue: ${c.hue.toFixed(1)},
    layout: "${c.layout}",
    attribution: ${JSON.stringify(c.attribution)},
    attrs: {
${attrs}
    },
  },`;
    })
    .join("\n");

  const out = `// GENERATED by \`pnpm scrape\` (bench/scrape/run.ts) — do not hand-edit.
// Real design-attribute vectors extracted from live sites' CSS. Kept as a
// plain static module so the shipped app never scrapes anything at runtime.
import type { InspirationCard } from "./corpus";

type RawScraped = Omit<InspirationCard, "kind">;

export const SCRAPED_CORPUS: RawScraped[] = [
${entries}
];
`;
  writeFileSync(fileURLToPath(new URL("../../src/corpus/scraped.ts", import.meta.url)), out);
  process.stderr.write(`wrote src/corpus/scraped.ts\n`);
}

main();
